이 문장 안에는 수식 $x$ 와 $\alpha^{\beta}$가 있습니다.

$$ v = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$

In [76]:
import numpy as np

In [77]:
a = np.array([[1],[3]])
a
b = np.array([[1,2]])
b*a

array([[1, 2],
       [3, 6]])

In [78]:
0.1+0.2 == 0.3

False

In [79]:
%precision %r
0.1+0.2

0.30000000000000004

In [80]:
%precision %r
0.3

0.3

In [81]:
from numpy import linalg

보스턴 집값 문제를 선형 예측 모형 으로 풀었을 때의 가중치 벡터 w를 구하라. 행렬과 벡터 데이터는 다음과 같이 얻을 수 있다. 여기에서는 문제를 간단하게 하기 위해 입력 데이터를 crim, nox, rm, age의 4종류로 제한하였고 데이터도 4개만 사용하였다.

In [82]:
from sklearn.datasets import load_boston

In [83]:
boston = load_boston()

In [84]:
X = boston.data
y = boston.target

In [85]:
A = X[:]
b = y[:]

In [86]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([ -9.1629784312186907113684242176532279700040817260742187500e-02,
         4.8675120340927455209190100049454485997557640075683593750e-02,
        -3.7793000553380806660896951143513433635234832763671875000e-03,
         2.8563675116042528401294475770555436611175537109375000000e+00,
        -2.8807793263207788214685933780856430530548095703125000000e+00,
         5.9252143180827818724765165825374424457550048828125000000e+00,
        -7.2244792886878572701903067354578524827957153320312500000e-03,
        -9.6799523983888757783233813825063407421112060546875000000e-01,
         1.7044339286755194606826080416794866323471069335937500000e-01,
        -9.3892537326736302816243551205843687057495117187500000000e-03,
        -3.9242567959248464415367152469116263091564178466796875000e-01,
         1.4983210248387557328442198922857642173767089843750000000e-02,
        -4.1697262352837505261504702502861618995666503906250000000e-01])

In [87]:
Apinv = np.dot(np.linalg.inv(np.dot(A.T, A)), A.T)
Apinv

array([[  1.0745182573817874604419492223783549889049027115106582642e-04,
          8.7791632519960779057650868129059062994201667606830596924e-05,
          1.4171465802620812645708225918639300289214588701725006104e-04,
        ...,
          9.7386790436106425807895325963414734360412694513797760010e-05,
          9.5918273445365768753619051256720240417052991688251495361e-05,
          8.7671544689158178889458461480188589121098630130290985107e-05],
       [ -4.7211348771108306479182131765170993276115041226148605347e-05,
         -1.2181335755444844541790783143397902676952071487903594971e-04,
         -1.6333855529091732003768577818902940634870901703834533691e-04,
        ...,
          9.2545945572693186285777311450573279216769151389598846436e-05,
          8.6247780935397785613376331337320834791171364486217498779e-05,
          1.0303743977022072376981132180162603617645800113677978516e-04],
       [ -1.0496246699281557880623072520620553405024111270904541016e-03,
          9.38480709216

In [88]:
i = np.dot(Apinv, b)
i

array([ -9.1629784312170503568495405488647520542144775390625000000e-02,
         4.8675120340877620073172238335246220231056213378906250000e-02,
        -3.7793000553171668398633187280211132019758224487304687500e-03,
         2.8563675116026496780818888510111719369888305664062500000e+00,
        -2.8807793263264600547302052291342988610267639160156250000e+00,
         5.9252143180830962876370904268696904182434082031250000000e+00,
        -7.2244792886855960581393709674102865392342209815979003906e-03,
        -9.6799523983902624468811382030253298580646514892578125000e-01,
         1.7044339286756382545462429334293119609355926513671875000e-01,
        -9.3892537326738662040170879663492087274789810180664062500e-03,
        -3.9242567959243812580893973063211888074874877929687500000e-01,
         1.4983210248388400404051523651105526369065046310424804688e-02,
        -4.1697262352835362531067175950738601386547088623046875000e-01])

In [89]:
np.dot(A, i)

array([ 29.10255503868592086291755549609661102294921875     ,
        24.50656965410092880119918845593929290771484375     ,
        31.23177939756964605066968942992389202117919921875  ,
        29.71046643059391811902969493530690670013427734375  ,
        29.56672407450584927346426411531865596771240234375  ,
        25.2978105295191113555119954980909824371337890625   ,
        21.531455168214048256913883960805833339691162109375 ,
        19.101116228100867289185771369375288486480712890625 ,
        11.085058398026848891504414496012032032012939453125 ,
        18.25808348812670800498381140641868114471435546875  ,
        19.33021710365687084731689537875354290008544921875  ,
        20.417589496526328929348892415873706340789794921875 ,
        19.663554088788256279940469539724290370941162109375 ,
        20.668437695050339897306912462227046489715576171875 ,
        20.52557495057899217272279202006757259368896484375  ,
        20.12101639683312015449700993485748767852783203125  ,
        

In [90]:
b

array([ 24.                                                  ,
        21.60000000000000142108547152020037174224853515625   ,
        34.7000000000000028421709430404007434844970703125    ,
        33.39999999999999857891452847979962825775146484375   ,
        36.2000000000000028421709430404007434844970703125    ,
        28.699999999999999289457264239899814128875732421875  ,
        22.89999999999999857891452847979962825775146484375   ,
        27.10000000000000142108547152020037174224853515625   ,
        16.5                                                 ,
        18.89999999999999857891452847979962825775146484375   ,
        15.                                                  ,
        18.89999999999999857891452847979962825775146484375   ,
        21.699999999999999289457264239899814128875732421875  ,
        20.39999999999999857891452847979962825775146484375   ,
        18.199999999999999289457264239899814128875732421875  ,
        19.89999999999999857891452847979962825775146484

In [99]:
A = (np.arange(9) - 4).reshape((3, 3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [103]:
import math

In [106]:
print(math.sqrt(60))

np.linalg.norm(A)

7.745966692414834


7.745966692414834

In [108]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])