### Reference
- http://www.numpy.org/
- http://aikorea.org/cs231n/python-numpy-tutorial/

### Install
- pip3 install numpy

### Make
- array
- reshape
- index
- zeros
- ones
- eye
- like
- empty
- arange
- linespace, logspace
- rand, randn
- stack
- concatenate
- split
- sort

In [1]:
import numpy as np

##### array
- ndim : 행렬의 차원
- shape : 행렬의 모양

In [2]:
# 1차원 배열 (vector)
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [3]:
# 2차원 배열 (1*3 matrix)
array = np.array([[0],[1],[2]]) 
print(array)

[[0]
 [1]
 [2]]


In [6]:
# 2차원 배열 (2*3 matrix)
array = np.array([
    [0,1,2],
    [3,4,5]
]) 
print(array)
print(array.ndim, array)

[[0 1 2]
 [3 4 5]]
2 [[0 1 2]
 [3 4 5]]


In [13]:
# 3차원 배열 (2*3*4 matrix)
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
]) 
print(array)
print(array.ndim, array.shape) # 바깥에서 안으로 모양을 나타낸다고 생각하면 편함

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3 (2, 3, 4)


##### reshape
- 행렬의 모양을 바꿀수 있다.

In [8]:
na = np.array([1,2,3,4,5,6,7,8])
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
rna = np.reshape(na,(4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
# 전치행렬
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

##### index
- 행렬의 특정 위치 데이터 값 가져오기
- 행렬 자르기

In [228]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [229]:
print(array[1][1][2])
print(array[1,1,2])

100
100


In [230]:
result = array[1:,1:,2:]
print(result)
print(result.ndim, result.shape)

[[[100   7]
  [ 10  11]]]
3 (1, 2, 2)


In [237]:
result[0][0]

array([100,   7])

In [238]:
result[0].ndim

2

##### zeros
- 행렬을 만들고 안에 0으로 채워 넣는다.

In [25]:
# 1차원
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

[ 0.  0.  0.  0.  0.]
1 (5,)


In [26]:
# 2차원 (2*3)
z = np.zeros((2,3))
print(z)
print(z.ndim, z.shape)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
2 (2, 3)


In [27]:
# 3차원 (2*3*4)
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
3 (2, 3, 4)


##### ones
- 행렬을 만들고 안에 1을 채워 넣는다.

In [28]:
# 3차원 (2*3*4)
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
3 (2, 3, 4)


##### eye
- 단위 행렬 데이터를 만든다.

In [241]:
# 단위행렬
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

##### like
- 행렬 안에 있는 모든 데이터를 0이나 1로 바꿀수 있다.

In [32]:
z

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [33]:
ls = np.ones_like(z)
print(ls)
print(ls.ndim, ls.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
3 (2, 3, 4)


In [34]:
o

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [35]:
ls = np.zeros_like(o)
print(ls)
print(ls.ndim, ls.shape)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
3 (2, 3, 4)


##### empty
- 빈행렬을 만든다.
- 실제로는 빈데이터가 아니라 더미 데이터가 들어간다

In [242]:
# 1.72e-5 -> 1.72 * 10 ** -5

a = np.empty((5,5))
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


##### arange
- range와 같다.
- 하지만 큰데이터에서 range 보다 속도가 빠르다

In [39]:
# range와 arange의 속도 비교
size = int(1E6) # E : exponential
%timeit for x in range(size): x ** 2
%timeit for x in np.arange(size): x ** 2
size

1 loop, best of 3: 532 ms per loop
1 loop, best of 3: 258 ms per loop


1000000

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [42]:
np.arange(2,10,3)

array([2, 5, 8])

In [43]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

##### linspace, logspace

In [45]:
np.linspace(0, 100, 4)

array([   0.        ,   33.33333333,   66.66666667,  100.        ])

In [46]:
# log10(x)=2, log10(x)=2.5, log10(x)=3
# 10**2, 10**2.5, 10**3
print(np.logspace(2, 4, 3))
print(np.logspace(2, 3, 3))

[   100.   1000.  10000.]
[  100.           316.22776602  1000.        ]


In [47]:
10**2, 10**2.5, 10**3

(100, 316.22776601683796, 1000)

##### random
- seed
- rand (uniform)
- randn (gaussian)
- randint
- shuffle
- choice

In [162]:
np.random.seed(0)
rd = np.random.rand(10)   # uniform 으로 난수 발생  (균등분포)
rdn = np.random.randn(10) # gaussian 으로 난수 발생 (정규분포 - 0에 가까운수가 많이 나옴)
print(rd)
print(rdn)

[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411
  0.43758721  0.891773    0.96366276  0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [62]:
# e-01 -> (10**-1)
np.random.seed(1)
rd = np.random.rand(4)
rdn = np.random.randn(4)
print(rd)
print(rdn)

[  4.17022005e-01   7.20324493e-01   1.14374817e-04   3.02332573e-01]
[-0.52817175 -1.07296862  0.86540763 -2.3015387 ]


In [63]:
r = np.random.rand(2,3,4)
print(r)

[[[ 0.41919451  0.6852195   0.20445225  0.87811744]
  [ 0.02738759  0.67046751  0.4173048   0.55868983]
  [ 0.14038694  0.19810149  0.80074457  0.96826158]]

 [[ 0.31342418  0.69232262  0.87638915  0.89460666]
  [ 0.08504421  0.03905478  0.16983042  0.8781425 ]
  [ 0.09834683  0.42110763  0.95788953  0.53316528]]]


In [72]:
r = np.random.randint(0,10,(3,3)) # randint는 마지막 숫자를 포함하지 않는다. 10이 아닌 9까지포함
r

array([[1, 2, 7],
       [2, 6, 0],
       [9, 2, 6]])

In [95]:
r = np.random.randint(10, size=(3,4)) # start value를 적어주지 않을때는 자동으로 0이다. (0 ~ 9까지)
r

array([[4, 3, 3, 6],
       [7, 3, 5, 3],
       [2, 4, 4, 0]])

In [107]:
# shuffle로 데이터의 순서를 바꿀수 있다.
np.random.shuffle(r)
r

array([[2, 4, 4, 0],
       [7, 3, 5, 3],
       [4, 3, 3, 6]])

In [147]:
# p의 확률로 range(5)를 10개 추출
print(list(range(5)))
print([0.1,0,0.3,0.6,0])
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.599, 0.001])

[0, 1, 2, 3, 4]
[0.1, 0, 0.3, 0.6, 0]


array([3, 2, 2, 3, 2, 3, 2, 3, 2, 3], dtype=int64)

In [148]:
r

array([[2, 4, 4, 0],
       [7, 3, 5, 3],
       [4, 3, 3, 6]])

In [158]:
# unique로 데이터의 유일한 값에 대한 리스트와 값의 갯수를 구할수 있다
# np.unique(r)
index, count = np.unique(r, return_counts=True)
print(index) 
print(count)

[0 2 3 4 5 6 7]
[1 1 4 3 1 1 1]


##### stack
- 행렬을 쌓는것과 같이 합치는 방법

In [166]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [167]:
na3 = np.stack((na1, na2)) # axis = 0 가로축, axis = 1 세로축
print(na3, na3.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


In [168]:
na3 = np.stack((na1, na2), axis=1)
print(na3, na3.shape)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]] (6, 2)


In [169]:
# practice 1
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])    
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [170]:
# 수직으로 합치기
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [171]:
# 수평으로 합치기. 하지만 리스트가 된다
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [178]:
# 수평으로 합치기
data = [list(range(7)[i:i+3]) for i in range(5) ] 
print(data)
np.stack(data, axis=-1) # axis = -1과 1이 같다.

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [179]:
# practice 2
np.arange(5)[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

##### concatenate (결합)
- 가로 결합은 열의 갯수가 같아야 한다.
- 세로 결합은 행의 갯수가 같아야 한다.

In [243]:
r1 = np.random.randint(10, size=(2,3))
print(r1)

[[5 9 0]
 [2 7 2]]


In [244]:
r2 = np.random.randint(10, size=(3,2))
print(r2)

[[9 2]
 [3 3]
 [2 3]]


In [245]:
r3 = np.random.randint(10, size=(3,3))
print(r3)

[[4 1 2]
 [9 1 4]
 [6 8 2]]


In [246]:
# 가로 결합
np.concatenate([r1, r3], axis=0) # column의 갯수가 같아야 한다. (r1과 r2는 가로결합 불가능)

array([[5, 9, 0],
       [2, 7, 2],
       [4, 1, 2],
       [9, 1, 4],
       [6, 8, 2]])

In [247]:
# 세로 결합
np.concatenate([r2, r3], axis=1)

array([[9, 2, 4, 1, 2],
       [3, 3, 9, 1, 4],
       [2, 3, 6, 8, 2]])

##### split

In [202]:
r = np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
r1 = np.split(r, [5]) # 앞에서 5번째를 기준으로 나눈다
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [210]:
# r1에는 나눈 데이터의 첫번째 데이터가 r2에는 나눈 데이터의 두번째 데이터가 들어간다
r1, r2 = np.split(r, [5]) 
r1, r2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [211]:
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8]) # 2,4,6,8을 기준으로 나눠 5개의 array 데이터가 생성된다.
r1, r2, r3, r4, r5

(array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]))

##### vsplit/hsplit
- 행렬을 수직, 수평으로 나눈다

In [212]:
r = np.random.randint(10, size=(4,6))
r

array([[0, 3, 5, 9, 4, 4],
       [6, 4, 4, 3, 4, 4],
       [8, 4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3, 0]])

In [213]:
# 수평으로 2개씩 자름
r1, r2 = np.vsplit(r, [2])
print(r1)
print(r2)

[[0 3 5 9 4 4]
 [6 4 4 3 4 4]]
[[8 4 3 7 5 5]
 [0 1 5 9 3 0]]


In [214]:
# 수직으로 3개씩 자름
r1, r2 = np.hsplit(r, [3])
print(r1)
print(r2)

[[0 3 5]
 [6 4 4]
 [8 4 3]
 [0 1 5]]
[[9 4 4]
 [3 4 4]
 [7 5 5]
 [9 3 0]]


In [215]:
# 수직으로 2개씩 자름
r1, r2, r3 = np.hsplit(r, [2,4])
print(r1)
print(r2)
print(r3)

[[0 3]
 [6 4]
 [8 4]
 [0 1]]
[[5 9]
 [4 3]
 [3 7]
 [5 9]]
[[4 4]
 [4 4]
 [5 5]
 [3 0]]


##### sort

In [216]:
r1 = np.random.randint(10, size=(3,3))
print(r1)

[[5 0 1]
 [2 4 2]
 [0 3 2]]


In [218]:
# 가로로 sorting
r1.sort() # axis -1과 1은 같은 동작을 한다
r1

array([[0, 1, 5],
       [2, 2, 4],
       [0, 2, 3]])

In [219]:
# 세로로 sorting
r1.sort(axis=0) 
r1

array([[0, 1, 3],
       [0, 2, 4],
       [2, 2, 5]])

In [220]:
# 문제
# 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
# 만든 행렬을 무작위로 섞으세요

In [221]:
result = np.arange(1,10)
result

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
result = np.reshape(result, (3,3))
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [223]:
result.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [225]:
np.random.shuffle(result)
result

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [226]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [227]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])