### Datatype
- boolean : bool
- integer : int64
- float : float64
- byte String : S24
- unicode String : U24

In [1]:
import numpy as np

In [2]:
na = np.array([True, False])
na.dtype

dtype('bool')

In [6]:
na = np.array([1, 2, 3])
na.dtype

dtype('int32')

In [7]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

##### change datatype

In [9]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

na = na.astype('int64')
print(na)

na = na.astype('bool')
print(na)

na = na.astype('S24')
print(na)

na = na.astype('U24')
print(na)

[-1.   0.   1.   2.2  3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
[b'True' b'False' b'True' b'True' b'True']
['True' 'False' 'True' 'True' 'True']


In [13]:
# 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬
na = np.random.rand(5,5)
print(na)

na = (na*6+5).astype('int64')
print(na)

[[  3.91391349e-01   7.18871082e-01   5.02500965e-04   5.71513890e-01
    8.18451999e-01]
 [  1.20729278e-01   8.76937171e-01   1.51271766e-01   3.41936621e-02
    8.43367359e-01]
 [  9.22889703e-01   5.90013511e-01   4.10758757e-01   9.70026319e-01
    7.05026385e-01]
 [  9.54036048e-01   8.61388357e-01   7.85166390e-02   5.86498984e-02
    9.35344583e-02]
 [  6.63791155e-01   6.57247844e-01   1.02528203e-01   3.09632121e-01
    2.49105969e-01]]
[[ 7  9  5  8  9]
 [ 5 10  5  5 10]
 [10  8  7 10  9]
 [10 10  5  5  5]
 [ 8  8  5  6  6]]
